language: cpp
dist: bionic
os: linux
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install libboost-all-dev
script:
  - ./ciScripts/unitTestScript.sh
branches:
  only:
    - master
    - ci_configuration
    - "/^v\\d+\\./"
